### ISSUE TITLE
Error, opencv2/core/utility.hpp not found

### ISSUE THREAD

**Issue by robhawkins** [ComputerVisionCentre/RRC2015_Baseline_CV3Tess#1]
Which version of opencv2 did you use?  I get the following error with opencv2 2.4.11

```
main.cpp:15:10: fatal error: 'opencv2/core/utility.hpp' file not found
```

I read that some functions in this file [may have been moved around](http://answers.opencv.org/question/14755/opencv2coreultilityhpp-not-found/).

**Comment by lluisgomez** [comment]
Dear robhawkins,
This code makes use of OpenCV 3.0 and opencv_contrib text modules.

**Comment by robhawkins** [comment]
Oh okay, I'll try again with OpenCV 3.0 + contrib and close this issue =)
